### ISSUE TITLE
create a login page

### ISSUE THREAD

**Issue by geethikalekha507** [geethikalekha507/lms-259#2]
1. create a **login screen** with **two text input fields**
2. create **login button** for confirmation
![Screenshot_24-5-2024_134042_www w3schools com](https://github.com/geethikalekha507/lms-259/assets/170608877/e9459e8a-0710-4571-955b-3b5979ffc31d)

**Comment by akhilabommireddy10** [comment]
login completed
![Uploading Screenshot_26-5-2024_183223_.jpeg…]()
